// login
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER';

// site location
export const LOCATION_LOADING = 'LOCATION_LOADING';
export const LOCATION_POPUP = 'LOCATION_POPUP';
export const LOCATION_UPDATE = 'LOCATION_UPDATE';
export const LOCATION_DELETE = 'LOCATION_DELETE';

// cart
export const CART_LOADING = 'CART_LOADING';
export const CART_POPUP = 'CART_POPUP';
export const CART_UPDATE = 'CART_UPDATE';
export const CART_CLEAR = 'CART_CLEAR';
export const CART_ITEM_ADD = 'CART_ITEM_ADD';
export const CART_ITEM_UPDATE = 'CART_ITEM_UPDATE';
export const CART_ITEM_DELETE = 'CART_ITEM_DELETE';
export const CART_ITEM_QTY_PLUS = 'CART_ITEM_QTY_PLUS';
export const CART_ITEM_QTY_MINUS = 'CART_ITEM_QTY_MINUS';

// popups
export const POPUP_CUST_LOGIN = 'POPUP_CUST_LOGIN';
export const POPUP_CUST_SIGNUP = 'POPUP_CUST_SIGNUP';
export const POPUP_COOK_SIGNUP = 'POPUP_COOK_SIGNUP';
export const POPUP_CUST_FORGOT_PWD = 'POPUP_CUST_FORGOT_PWD';
export const POPUP_MY_ORDERS = 'POPUP_MY_ORDERS';



